// @vitest-environment jsdom
import { fireEvent, render, screen, within } from '@testing-library/react'; import { describe, expect, it } from 'vitest'; import { HistoryPage } from '../../src/renderer/pages/history-page'; import type { Journal, Project, Review } from '../../src/shared/schemas/domain';
const project: Project = { schemaVersion: 1, id: 'project_a1', name: '求职', status: 'active', createdAt: '2026-08-01T00:00:00.000Z', archivedAt: null };
const journal: Journal = { schemaVersion: 1, id: 'journal_a1', date: '2026-08-12', createdAt: '2026-08-12T00:00:00.000Z', updatedAt: '2026-08-12T00:00:00.000Z', projectIds: ['project_a1'], body: '<script>不能执行</script> 求职日志' };
const review: Review = { schemaVersion: 1, id: 'review_a1', type: 'weekly', periodStart: '2026-08-10', periodEnd: '2026-08-16', sourceIds: ['journal_a1'], projectId: 'project_a1', provider: 'openai-compatible', model: 'fake', promptVersion: 'weekly-review-v1', createdAt: '2026-08-16T00:00:00.000Z', body: '本周复盘正文' };
describe('HistoryPage', () => {
  it('merges records newest first and opens full safe text with sources', () => { render(<HistoryPage journals={[journal]} reviews={[review]} projects={[project]}/>); expect(screen.getAllByRole('button', { name: /本周复盘正文|求职日志/ })[0]).toHaveAccessibleName(/本周复盘正文/); fireEvent.click(screen.getByRole('button', { name: /求职日志/ })); expect(within(document.querySelector('.history-reader') as HTMLElement).getByText('<script>不能执行</script> 求职日志', { selector: 'pre' })).toBeInTheDocument(); expect(document.querySelector('script')).toBeNull(); });
  it('combines type, text and project filters and explains an empty result', () => { render(<HistoryPage journals={[journal]} reviews={[review]} projects={[project]}/>); fireEvent.change(screen.getByLabelText('记录类型'), { target: { value: 'journal' } }); fireEvent.change(screen.getByLabelText('搜索历史'), { target: { value: '不存在' } }); fireEvent.change(screen.getByLabelText('项目筛选'), { target: { value: 'project_a1' } }); expect(screen.getByText('没有符合筛选条件的记录')).toBeInTheDocument(); });
});
