import { useState } from 'react';
import type { Project } from '../../shared/schemas/domain';
const today = new Date().toISOString().slice(0, 10);
export function ReviewsPage({ projects }: { projects: Project[] }) {
  const [type, setType] = useState<'weekly' | 'monthly' | 'project'>('weekly'); const [start, setStart] = useState(today); const [end, setEnd] = useState(today); const [projectId, setProjectId] = useState('');
  const [preview, setPreview] = useState<Awaited<ReturnType<typeof window.zhiji.reviews.preview>> | null>(null); const [message, setMessage] = useState('先选择范围并预览材料');
  const input = { type, start, end, ...(type === 'project' && projectId ? { projectId } : {}) };
  const loadPreview = async () => { try { const value = await window.zhiji.reviews.preview(input); setPreview(value); setMessage(`已找到 ${value.sources.length} 条材料，请确认后生成`); } catch (error) { setMessage(`无法预览：${error instanceof Error ? error.message : '范围内没有材料'}`); } };
  const generate = async () => { if (!preview) return; setMessage('正在生成复盘…'); try { await window.zhiji.reviews.generatePeriodic({ ...input, previewToken: preview.token }); setPreview(null); setMessage('复盘已保存到本机'); } catch (error) { setMessage(`生成失败：${error instanceof Error ? error.message : '请检查设置'}`); } };
  return <><header><div><h2>复盘</h2><p>先确认日期与材料，再调用你的模型。</p></div></header><section className="card settings-form"><label>复盘类型</label><select value={type} onChange={(e) => { setType(e.target.value as typeof type); setPreview(null); }}><option value="weekly">周报</option><option value="monthly">月报</option><option value="project">项目复盘</option></select>{type === 'project' && <><label>项目</label><select value={projectId} onChange={(e) => setProjectId(e.target.value)}><option value="">可不选，仅按日期</option>{projects.map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</select></>}<label>开始日期</label><input type="date" value={start} onChange={(e) => { setStart(e.target.value); setPreview(null); }}/><label>结束日期</label><input type="date" value={end} onChange={(e) => { setEnd(e.target.value); setPreview(null); }}/><div className="actions"><span>{message}</span><button onClick={() => void loadPreview()}>预览材料</button><button className="primary" disabled={!preview} onClick={() => void generate()}>确认并生成</button></div></section>{preview && <section><h3>本次材料</h3>{preview.sources.map((s) => <article className="row" key={s.id}><b>{s.date}</b><span>{s.excerpt}</span></article>)}</section>}</>;
}
