import { useEffect, useMemo, useState } from 'react';
import type { Journal, Project, Review } from '../../shared/schemas/domain';
import type { AppView } from '../app/navigation';
import { Button } from '../components/button';
import { EmptyState } from '../components/empty-state';
import { Field } from '../components/field';
import { PageHeader } from '../components/page-header';
import { StatusBanner } from '../components/status-banner';

const today = new Date().toISOString().slice(0, 10);
const displayDate = new Intl.DateTimeFormat('zh-CN', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'long' }).format(new Date(`${today}T12:00:00`));

export function TodayPage({ journals, projects, reviews, onRefresh, onNavigate }: { journals: Journal[]; projects: Project[]; reviews: Review[]; onRefresh(): Promise<void> | void; onNavigate(view: AppView): void }) {
  const todayJournal = journals.find((item) => item.date === today);
  const [body, setBody] = useState(todayJournal?.body ?? ''); const [projectId, setProjectId] = useState(todayJournal?.projectIds[0] ?? ''); const [saveState, setSaveState] = useState<'idle' | 'loading' | 'success' | 'error'>('idle'); const [saveMessage, setSaveMessage] = useState(''); const [reviewState, setReviewState] = useState<'idle' | 'loading' | 'success' | 'error'>('idle'); const [reviewMessage, setReviewMessage] = useState('');
  const [generatedReview, setGeneratedReview] = useState<Review | null>(null);
  useEffect(() => { if (todayJournal && saveState === 'idle') { setBody(todayJournal.body); setProjectId(todayJournal.projectIds[0] ?? ''); } }, [todayJournal?.id]);
  const latestDaily = useMemo(() => reviews.filter((item) => item.type === 'daily' && item.periodEnd < today).sort((a, b) => b.periodEnd.localeCompare(a.periodEnd))[0], [reviews]);
  const weekStart = new Date(`${today}T12:00:00`); weekStart.setDate(weekStart.getDate() - ((weekStart.getDay() || 7) - 1)); const weekStartIso = weekStart.toISOString().slice(0, 10); const weeklyJournals = journals.filter((item) => item.date >= weekStartIso && item.date <= today);
  const save = async () => { if (!body.trim()) return null; setSaveState('loading'); setSaveMessage(''); try { const saved = await window.zhiji.journals.save({ id: todayJournal?.id, date: today, body, projectIds: projectId ? [projectId] : [] }); setSaveState('success'); setSaveMessage('已保存到本机'); await onRefresh(); return saved; } catch (reason) { setSaveState('error'); setSaveMessage(`保存失败：${reason instanceof Error ? reason.message : '请稍后重试'}`); return null; } };
  const generate = async () => { setReviewState('loading'); setReviewMessage('正在根据今日日志生成反馈…'); try { const journal = todayJournal ?? await save(); if (!journal) { setReviewState('error'); setReviewMessage('请先写下并保存今日日志'); return; } const result = await window.zhiji.reviews.generateDaily({ journalId: journal.id }); setGeneratedReview(result); await onRefresh(); setReviewState('success'); setReviewMessage(result.body); } catch (reason) { setReviewState('error'); setReviewMessage(`生成失败：${reason instanceof Error ? reason.message : '请检查 AI 设置'}`); } };
  const recent = journals.filter((item) => item.date !== today).slice().reverse().slice(0, 3);
  return <><PageHeader title="写下今天发生的事" description="不用套模板，真实地写就够了。" action={<span className="tag">{displayDate}</span>}/><div className="today-grid"><section className="card editor-card"><Field label="关联项目（可选）"><select value={projectId} onChange={(event) => { setProjectId(event.target.value); setSaveState('idle'); }}><option value="">不关联项目</option>{projects.filter((item) => item.status === 'active').map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="今日日志"><textarea aria-label="今日日志" value={body} onChange={(event) => { setBody(event.target.value); setSaveState('idle'); }} placeholder="发生了什么？你做了什么？结果怎样？"/></Field><div className="editor-meta"><span className="tag">明确保存</span><span className="tag">{body.length} 字</span></div>{saveMessage && <StatusBanner tone={saveState === 'error' ? 'error' : 'success'}>{saveMessage}</StatusBanner>}<div className="button-row"><Button variant="ghost" loading={saveState === 'loading'} disabled={!body.trim()} onClick={() => void save()}>仅保存日志</Button><Button variant="primary" loading={reviewState === 'loading'} disabled={!body.trim()} onClick={() => void generate()}>生成今日反馈</Button></div>{reviewMessage && <StatusBanner tone={reviewState === 'error' ? 'error' : reviewState === 'success' ? 'success' : 'info'}>{reviewMessage}</StatusBanner>}</section><aside className="today-side"><section className="card action-card"><h3>上次行动待验证</h3>{latestDaily ? <><p>{latestDaily.body.split('\n').find((line) => line.startsWith('- '))?.slice(2) ?? '查看上一次反馈中的行动。'}</p><span className="muted">来自 {latestDaily.periodEnd} 日反馈</span><Button variant="secondary" onClick={() => onNavigate('history')}>查看完整反馈</Button></> : <EmptyState title="暂无待验证行动" description="生成第一份日反馈后，这里会提醒你验证行动。"/>}</section><section className="card week-card"><h3>本周闭环</h3><p><strong>{weeklyJournals.length}</strong> 篇日志 · <strong>{reviews.filter((item) => item.type === 'daily' && item.periodStart >= weekStartIso).length}</strong> 次日反馈</p><p className="muted">把一周材料放在一起，检查行动是否真的有效。</p><Button variant="secondary" onClick={() => onNavigate('reviews')}>查看复盘入口</Button></section></aside></div><section className="recent-section"><div className="section-heading"><h3>最近记录</h3><button onClick={() => onNavigate('history')}>查看全部</button></div>{recent.length ? <div className="recent-list">{recent.map((item) => <article className="recent-item" data-testid="recent-journal" key={item.id}><time>{item.date}</time><span>{item.body.slice(0, 80)}</span></article>)}</div> : <EmptyState title="还没有历史记录" description="保存今天的日志后，它会出现在这里。"/>}</section></>;
}
